### ISSUE TITLE
Auth Refresh Token - 13

### ISSUE THREAD

**Issue by Parkerhiphop** [Game-as-a-Service/Game-Lobby-Web#115]
不然30鐘一過就會到期401，需要跟後端討論整體流程

![Screen Shot 2023-05-29 at 23 22 33](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/45290853/7e9fb63d-5a27-41ad-8552-77972af5166b)

**Comment by HongLinLiao** [comment]
JWT Token expire 30min later.
Need a refresher every 15min get new token

**Comment by IamSaker** [comment]
之後會換另外的 solution 來做到 refresh token，先 close issue
