### ISSUE TITLE
第三方登入 API 串接整合 剩剛剛討論最後一步前端接token - 5

### ISSUE THREAD

**Issue by Parkerhiphop** [Game-as-a-Service/Game-Lobby-Web#119]
![Screen Shot 2023-05-29 at 23 27 34](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/45290853/1deff750-45a7-4452-967f-fbf0053be1a2)

**Comment by IamSaker** [comment]
已完成，close issue
