### ISSUE TITLE
Refactor: Extract WebSocket Service - 5

### ISSUE THREAD

**Issue by Parkerhiphop** [Game-as-a-Service/Game-Lobby-Web#185]
Why?
- websocket 會在很多地方被用到，但目前直接在 `pages/api/mock/socket.ts` 用到的地方寫很多設定

What?
把 Websocket 包成一個可以重複利用的 service / hooks
- connect
- on('event')
- disconnect

**Comment by Yuwen-ctw** [comment]
Hello, @Parkerhiphop 
　這個任務跟我所預期的的狀況不太一樣，我原本以為只會把 on('message') 包成hook，因此想釐清一下。

　上次 Spring 會議有詢問說後端的 websocket 是否只會有一個伺服器，得到的答案是 "是"，那目前就我的理解， websocket 是一個讓前後端連線後，就可持續性溝通的機制，因此我的假設是當使用者登入後會立即與後端 websocket 連線，一直到登出、關閉分頁、網路斷線或伺服器掛掉，它才會終止跟後端的溝通。　至於平台使用期間，無論是房間的事件（使用者加入、踢人等）或者聊天室（無論是大廳或房間內），都是用同一個端點，前端透過收到的 message data 依照事先與後端定義好的格式，來區分本次 message 是什麼類型的事件，去做對應的行為。
　
　因此我會認為 connect 與 disconnect 這兩個 websocket 事件在使用平台期間都只會觸發一次（暫不考慮斷線後嘗試重新連線的需求），這也是我當初直接把聊天室功能升級成 context 的原因，後續只要再另外定義 message 格式，就可以銜接房間事件、大廳聊天室或房間列表更新的事件。

　假如上述我對 websocket 的理解沒有錯的話，那對於此任務我的疑問是，如果把連線與斷線包成重複利用的 hook，代表在使用平台期間，websocket 會依據特定需求，頻繁地與後端的**同一個端點**進行連線與斷線嗎？　假如是，那是什麼情境會需要主動斷開唯一一個與後端的連線? ( 考量大廳聊天室應該是一個不會中斷的服務 )
