### ISSUE TITLE
Fix: usePopup 中的 Popup component 不正常渲染 bug

### ISSUE THREAD

**Issue by JohnsonMao** [Game-as-a-Service/Game-Lobby-Web#220]
我在實作進入房間時，發現 `Popup` 有會有不正常渲染的情況
我的想法是當使用 `usePopup` hook 的元件中狀態有改變時
導致每次回傳的 `Popup` 都是新的組件
就會造成畫面上的 `Popup` 會頻繁的閃爍
尤其在打 API 時狀態的改變尤為明顯

我有查了一下網路上其他人的想法
看到了一篇文章: https://blog.bitsrc.io/new-react-design-pattern-return-component-from-hooks-79215c3eac00
最後都改成用 Provide 與 Context 的方式實作了

如果想重現這個 bug
可以切換到 `feature/enter-room` 這個分支，並點選有鎖的房間輸入 **1111** 即可重現

**Comment by Yuwen-ctw** [comment]
Hello @JohnsonMao ,
我這邊確實可以重現這個 bug，輸入錯誤的密碼後並執行 API 後，只要 `Toast` 有顯示或消失均會造成 Popup 閃爍，而會造成此現象的原因，也認為是你所說的那樣，推測流程應該是 useRequest 觸發 `Toast`  -> toast context 改變 ->  `RoomListView` 重新渲染-> usePopup 重新執行 -> 產生新的 `Popup` -> `Modalow`觸發關閉再打開 -> 畫面閃爍。

目前我打算將 usePopup 裡面的函式與 `Popup` 元件分別使用 useCallback 與 useMemo 記憶起來，以解決此議題，而是否要使用 PopupContext 可以看大家的想法，決議後再添加。

另外還有一個發現，當輸入密碼 1111 得到失敗的回應，並於密碼彈窗關閉後，應顯示錯誤訊息的 `Popup `會出現後又立即消失，此狀況可能有另一個因素。

目前實驗是當 `Popup `元件不以 `Modalow `為基本 UI 時，並於得到失敗的回應且密碼彈窗關閉後，可以立即顯示 `Popup `的內容，而不會消失，因此推測是 `Modalow `元件的 useEffect 會在 isOpen 為 false 時，延後 200 毫秒才真正關閉 Modalow 的因素 ，可能的流程是：
得到失敗回應觸發`.catch` -> `firePopup`函式顯示`Popup` -> `.finally` 觸發 `setSelectedRoom(undefined)` -> `EnterPrivateRoomModal` 的 isOpen 為 false -> `Modalow `觸發 useEffect -> 200毫秒後將`Modalow `從 DOM 移除 ，而因此時於 DOM 上的是 `Popup` 而非觸發它的 `EnterPrivateRoomModal`，所以才會誤關閉了 `Popup`。

目前我打算將 Popup 的樣式改手刻，來緩解現行議題。

以上說明，若有其他想法可以再討論，預計周末才會動工，謝謝！
