### ISSUE TITLE
Feat: 首頁  socket echo input and toggle button - 3

### ISSUE THREAD

**Issue by Parkerhiphop** [Game-as-a-Service/Game-Lobby-Web#240]
# DoD
1. 在首頁放置 Echo Input（單純讓 WS 發出去後，後端可以傳一樣的資料回來）
2. Toggle Button 在 Production 時能控制要發送 websocket event 到 localhost 還是 production（方便後端可以即時測試）

![Screen Shot 2023-07-12 at 21 48 48](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/45290853/fda4b212-ac59-47e2-8398-dcc557f657d7)

**Comment by IamSaker** [comment]
目前沒有需求，先 close issue
