### ISSUE TITLE
Toast / Notification - 3

### ISSUE THREAD

**Issue by Parkerhiphop** [Game-as-a-Service/Game-Lobby-Web#29]
Story Points: 3

![Screen Shot 2023-05-29 at 23 16 22](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/45290853/18bb3eeb-d35d-4842-881f-0f8e51c6bf89)

**Comment by physicsSorcererKing** [comment]
我有點卡到，可能還需要兩天才會PR
