### ISSUE TITLE
fix: i18n Not Working in Production

### ISSUE THREAD

**Issue by JohnsonMao** [Game-as-a-Service/Game-Lobby-Web#291]
目前遇到的問題點是因為我們透過 docker 打包
其中有透過 dockerfile 來移動 public 資料夾位置
所以就找不到 public 資料夾
目前 next-i18next.config.js 似乎不是在根目錄
所以造成路徑上找不到檔案
![](https://user-images.githubusercontent.com/86179381/264313581-00bbd3cd-718e-4e49-a738-f54022127709.png)

**Comment by ttpss930141011** [comment]
Hello @JohnsonMao @Yuwen-ctw 

我這邊嘗試過後找到問題在哪了，懶人包：[Language Tag](https://www.ibm.com/docs/zh-tw/spectrum-protect/8.1.7?topic=options-language) 設定錯誤，有 `zh_TW`、`zh-Hans-TW` 但沒有 `zh-tw`。

| Development|Production|
|---|---|
|![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/1c4d72a6-ec84-4654-82a8-5ba05cbcbf7e)|![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/0192bc86-00d9-4925-8c4d-f7499d9168d5)|

更多請參考我 PR #296

可以看到改掉 Language Tag 後 response 內容已正常(原為空 {} )

<img width="400" src="https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/28f986ee-b106-4079-9568-a6551441c184"></img>

> ref: [can't seem to get language locales working](https://github.com/i18next/next-i18next/discussions/2125), [LANGUAGE](https://www.ibm.com/docs/zh-tw/spectrum-protect/8.1.7?topic=options-language), [Language Tags - OBSOLETE](https://www.iana.org/assignments/language-tags/language-tags.xhtml)

**Comment by JohnsonMao** [comment]
@ttpss930141011 可以先試試看合併這個改動在 Production 是否能正常顯示
（記得驗證註解的地方要恢復）

**Comment by ttpss930141011** [comment]
喔喔 那我就提 PR 來合了喔

**Comment by ttpss930141011** [comment]
已 merge 測試後正常：

|/|/rooms|
|--|--|
|![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/497ab199-0678-4e99-8c44-134bac004e65)|![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/fd4e7b89-738a-4d51-828c-a9c3b4e0a5f8)

這邊就先關閉 issue 了，感謝！
