### ISSUE TITLE
Vercel Preview 無法登入及臨時方案

### ISSUE THREAD

**Issue by allyusd** [Game-as-a-Service/Game-Lobby-Web#326]
目前 PR 上的 Vercel Preview，
登入頁會直接連到正式環境，無法登入 Preview。

臨時方案為手動從正式環境復製 token，
然後 F5 即可進入遊戲大廳。

**Comment by ricksu978** [comment]
@allyusd 
在後端開 ticket，然後關掉這張即可

**Comment by JohnsonMao** [comment]
暫不使用 Vercel
