### ISSUE TITLE
v2 - 遊戲大廳畫面

### ISSUE THREAD

**Issue by ricksu978** [Game-as-a-Service/Game-Lobby-Web#378]
Figma 設計稿
https://www.figma.com/file/ztRcNTiXJ4VVWksr8jrSGV/Design-2.0?type=design&node-id=58-2004&mode=design&t=PtGOmkjPI2mmiLj8-0

- [x] layout #392 
- [x] Carousel Component #349 
- [x] #395
- [x] #396
- [x] #397
- [x] #398

**Comment by JohnsonMao** [comment]
- [x] layout
- [ ] Carousel Component
- [ ] Command Component
- [ ] Tabs Component
- [ ] Dialog Component
- [ ] home page
- [ ] rooms page
- [ ] game page
