### ISSUE TITLE
CI / CD 會卡住

### ISSUE THREAD

**Issue by ricksu978** [Game-as-a-Service/Game-Lobby-Web#99]
0528:

#100 使用 `--production` 在 EC2 上只安裝必要的 dependencies，暫時有成功

後續需要再繼續追蹤上版是否穩定。

---

Logs from GitHub Action
https://github.com/Game-as-a-Service/Game-Lobby-Web/actions/runs/5103534766/jobs/9173894883
```
cd ~/game-lobby/frontend
yarn install --frozen-lockfile
======END======
out: yarn install v1.22.19
out: [1/4] Resolving packages...
out: [2/4] Fetching packages...
out: [3/4] Linking dependencies...
err: warning "@storybook/nextjs > css-loader@6.7.4" has unmet peer dependency "webpack@^5.0.0".
err: warning "@storybook/nextjs > node-polyfill-webpack-plugin@2.0.1" has unmet peer dependency "webpack@>=5".
err: warning "@storybook/nextjs > postcss-loader@7.3.1" has unmet peer dependency "webpack@^5.0.0".
err: warning "@storybook/nextjs > sass-loader@12.6.0" has unmet peer dependency "webpack@^5.0.0".
err: warning "@storybook/nextjs > style-loader@3.3.3" has unmet peer dependency "webpack@^5.0.0".
err: warning " > @testing-library/user-event@14.4.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
out: [4/4] Building fresh packages...
```
卡在最後一不, 使得整個 EC2 也掛掉。

請重新 review CI / CD 的指令，改用 Docker Container 也可以是考慮選項之一

**Comment by ricksu978** [comment]
@Parkerhiphop @HongLinLiao 
https://github.com/Game-as-a-Service/Game-Lobby-Web/actions/runs/5105434738/jobs/9177023387
昨天 CI / CD 又沒過，整台又當

說明一下，從觀測的資料來看
![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/35659961/d3eb5932-be63-468a-955c-a231c73af9ea)
1. 當下的 CPU 是 100% 的
2. 持續了 1 個小時後，Status Check 開始 Fail，CPU 也降下來。

**Comment by Parkerhiphop** [comment]
5/31 再上一次就成功了

**Comment by IamSaker** [comment]
推測是此 EC2 Instance Type 的 Memory 不給力

改善方案
1. `t2.micro` 升級成 `t3.micro`
2. tuning yarn install & build package 的部分

**Comment by ricksu978** [comment]
fixed by #137
